{% set name = "python-systemd" %}
{% set version = "235" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/systemd-python/systemd-python-{{ version }}.tar.gz
  sha256: 4e57f39797fd5d9e2d22b8806a252d7c0106c936039d1e71c8c6b8008e695c0a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
    - {{ cdt('systemd-devel') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - systemd
    - systemd.journal
    - systemd.daemon
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/systemd/python-systemd
  summary: Python interface for libsystemd
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timkpaine
    - isuruf
